### ISSUE TITLE
Slideshow at the Participate page 

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#114]
The slideshow at the participate page http://sfpc.io/participate/ never really worked in the mobile browser. It displays all the images. After [my commit](https://github.com/SFPC/sfpc.github.io/commit/fdedb37d0e1c77c6f503000ecf99ee958f9c3ff7), the slideshow is not working (Sorry, I broke it!) and Lauren has made changes to have single image on the landing page (until we fix the slideshow). I think this maybe a good time to think about slideshow on the participate page? Perhaps having a strong static image ([like this one](https://github.com/SFPC/sfpc.github.io/blob/master/static/img/participate/dayfornight_crowd.jpg))at the top and having slideshow in the bottom, or photos between the text can work?

**Comment by poohlaga** [comment]
Ahhhh, the JQuery script that runs the slider is hosted externally (code.builtbyevolve.com/nerveSlider/jquery.nerveSlider.min.js) and that site is no longer live at all. 

Will investigate a new option.

**Comment by tchoi8** [comment]
Ok. I'm color correcting the current image, and pushing the page with a static image for now.

**Comment by leee** [comment]
@tchoi8 @poohlaga nerveSlider is available again, and you probably want to have a local copy before it disappears again for some reason.

**Comment by poohlaga** [comment]
works works

**Comment by tchoi8** [comment]
cool. @leee thanks.
It's doing a funny thing of resizing when you first load the page. any tips on fixing it?

**Comment by leee** [comment]
*frowns*

I can't seem to replicate what you're describing - you're talking about `http://sfpc.io/participate/`? Do you think you can nab a gifv/video?
