### ISSUE TITLE
Slide resize

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#118]
When the page is loaded for the first time, there's a big gap below the image. ![image](https://cloud.githubusercontent.com/assets/683107/16534555/991a7b5a-3fae-11e6-80f0-7428b64fddc2.png)

and it resizes after the first image.

![image](https://cloud.githubusercontent.com/assets/683107/16534562/a8cac0a0-3fae-11e6-8553-6df962fb3e5a.png)

**Comment by poohlaga** [comment]
I uploaded a new version of the first slide the t=other day that was the same size as the other photos and it seems to fix the issue on my end. If you try loading the page in incognito or clearing cache it should fix it.

**Comment by solon** [comment]
Fixed in a90a106002009844b25754a60422db192f372f2b
