### ISSUE TITLE
Working on Fall 17 Call 

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#120]
Hi team, @ofZach @poohlaga 

I made Fall17 Participate page on the [fall17 branch](https://github.com/SFPC/sfpc.github.io/tree/fall17)  

and the call page is here
[https://github.com/SFPC/sfpc.github.io/blob/fall17/fall2017.md](https://github.com/SFPC/sfpc.github.io/blob/fall17/fall2017.md)
Can you check and confirm it's okay? 

- [ ]  Changed the language around class time and teachers. Now it says Mon~Thursday. Also changed the language around tuition and deposit 
- [ ]  Added new images from fall 15/16 showcase 

More things to work on 

- [ ]  Participate page and Fall 17 has some redundant information. Edit the language and make information more precise. 
- [ ] Update student and teachers bio and photo in Class page

**Comment by solon** [comment]
Looks like this was resolved in 8577bfe27d7e39dc514993a2d8b1dc2e59818628
