### ISSUE TITLE
Issues with two student profiles

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#139]
I'm having issues with Diana and Guillermo's profile

1. I fork the latest ![commit](https://github.com/SFPC/sfpc.github.io/commit/837e8f63ba28a67f25394d217e956d71ae53af8e) from master.
2. I make no changes.
3. I try to check out to a branch (to work on updates for Spring 2018 page)   

![image](https://user-images.githubusercontent.com/683107/31580452-25a9f046-b11e-11e7-9f27-ab6b42c73ab4.png)

and their profiles are seen as untracked files.
 
When I force checkout to 2018 and return to master 

![image](https://user-images.githubusercontent.com/683107/31580479-bfb8bca8-b11e-11e7-8d57-81edfd6f0710.png)

the files are seen as deleted.

Interestingly, the files do exist on local repo and have been untouched. 

![image](https://user-images.githubusercontent.com/683107/31580502-625b6870-b11f-11e7-9a58-68bb999de1f6.png)

Question 1: I'm wondering if this has anything to do with special Spanish characters in their names?
Question 2: I wonder if there are ways of avoiding this? For now I can work around by resetting to the latest commit on the master (git reset --hard @{u}) , but I feel there must be a better way.
 
I'll continue to investigate, and work around to create Spring 2018 page.

Thanks

**Comment by hansman** [comment]
From the error message after step 3 I think the following should be the case:

1) You checkout the current `HEAD` of the `master` branch
if you run `git status` you should see now 4 files in `_people` and `static` as untracked files. Those files were locally on your machine. You happen to checkout out a new branch. That is unrelated to your local 'untracked' files though.
2) No changes
3) You checkout branch `a` that happens to have those files that you have locally on your machine, untracked by git, contained in branch `a`. As a result you get a message saying `The following untracked files would be overwritten`. If you do the `-f` trick in the next step you overwrite those files without and don't get this error message again.

`The files do exist on local repo and have been untouched` 
In which branch? It sounds like they are in branch `a`, the branch from step 3, but not in the `master` branch.

**Comment by hansman** [comment]
This exists: 
https://git-scm.com/docs/git-config#git-config-coreprecomposeUnicode

**Comment by rileyjshaw** [comment]
Likely related, when I clone the repo I see the following:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  '_people/diana_sánchez.md'
  '_people/diana_sánchez.md'
  '_people/guillermo-montecinos-peña.md'
  '_people/guillermo-montecinos-peña.md'
  'static/img/people/diana_sánchez.jpg'
  'static/img/people/diana_sánchez.jpg'
  'static/img/people/guillermo_montecinos_peña.jpg'
  'static/img/people/guillermo_montecinos_peña.jpg'
```
