### ISSUE TITLE
Alumni name in testimonials 

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#155]
![image](https://user-images.githubusercontent.com/683107/38388849-7d7a6946-38ea-11e8-8899-1bfd52b5caeb.png)
Missing profile  http://sfpc.io/fall2018/  @heatherm

**Comment by solon** [comment]
Closing, as this testimonial was removed: https://github.com/SFPC/sfpc.github.io/commit/909028abd97f81ad29d49a52f823ffa76a5ae5bd#diff-29136b677b842c0eae38eed3f118b777L3-L4
