### ISSUE TITLE
svg is a little big in header

### ISSUE THREAD

**Issue by ofZach** [SFPC/sfpc.github.io#156]
hey @heatherm thanks for the changes! 

do you think it's possible to shrink the SVG a bit?  it comes in a little large and without a lot of white space with the menu -- the red box is closer to the previous size...

<img width="1096" alt="screen shot 2018-04-05 at 4 12 40 pm" src="https://user-images.githubusercontent.com/142897/38389421-63bb8e0c-38ec-11e8-9eed-2cdf75dece48.png">

thx!

**Comment by ofZach** [comment]
(ps, that's just from memory but it might be a bit larger than that -- maybe halfway between the red box and current dimensions)

**Comment by heatherm** [comment]
@ofZach yep, good catch! I'll push a fix shortly.

**Comment by solon** [comment]
Fixed in cf6cff228864d225e6a0c1777082a21617279e9f
