### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by tchoi8** [SFPC/sfpc.github.io#184]
I got Page build warning after merging following PR.
https://github.com/SFPC/sfpc.github.io/pull/183 @pcsteppan 
https://github.com/SFPC/sfpc.github.io/pull/181 @gregsadetsky 
https://github.com/SFPC/sfpc.github.io/pull/178 @rileyjshaw 

The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by rileyjshaw** [comment]
GitHub updated the addresses for custom domains a while ago – I looked into it<a name="back1" href="#ref1"><sup>1</sup></a> and you need to update them:

- Log in at https://www.gandi.net/en
- Find your [DNS settings page](https://docs.gandi.net/en/domain_names/common_operations/dns_records.html#editing-via-the-table-mode)
- You have an `A` record set up pointing to `192.30.252.154` (and maybe one to `192.30.252.153`?) Update them. You probably need four `A` records pointing to:
    - `185.199.108.153`
    - `185.199.109.153`
    - `185.199.110.153`
    - `185.199.111.153`

...then you'll hopefully be good to go! A cool side-effect of this is that in about a day, you'll be able to go into the site settings here and switch over to HTTPS 🤘

---

<a name="ref1" href="#back1">1</a>: Based on `dig sfpc.io +answer` it looks like your records are set up with Gandi and set to `192.30.252.154` (the old address).

**Comment by rileyjshaw** [comment]
Update: I've updated the IP addresses. Tomorrow I'll make a pull request to delete and re-add the [CNAME file](https://github.com/SFPC/sfpc.github.io/blob/master/CNAME), after which we should be able to switch to HTTPS and close this issue  🎉

**Comment by rileyjshaw** [comment]
Cool! I just ran a build and didn't encounter this error. Also, [sfpc.io](https://sfpc.io) now runs on HTTPS!

<img width="139" alt="Screen Shot 2019-04-23 at 08 19 39" src="https://user-images.githubusercontent.com/1840854/56595565-bad35f00-65a3-11e9-9d64-539337024d39.png">

Closing this issue.

**Comment by gregsadetsky** [comment]
@rileyjshaw just opened #186 to fix a small issue related to this.
