### ISSUE TITLE
Sarah Groff-Palermo's photo is 404

### ISSUE THREAD

**Issue by gregsadetsky** [SFPC/sfpc.github.io#185]
http://sfpc.io/people/sarah-groff-palermo/ shows a 404 image -- the `<img>` URL points to `http://sfpc.io/static/img/people/sarah_groff-palermo.jpg`

The image file does exist, but its URL is `http://sfpc.io/static/img/people/sarah_groff_palermo.jpg` (notice the underscores -- the 404 link has an underscore, and a dash)

**Comment by poohlaga** [comment]
Awesome heads up, thaaaankkkkks!!!!!
