### ISSUE TITLE
Sarah Groff-Palermo's photo is 404

### ISSUE THREAD

**Issue by gregsadetsky** [SFPC/sfpc.github.io#190]
Related to the closed #185, Sarah's photo is missing (404) on the list page https://sfpc.io/people/

In the list (i.e., the url above), the image is referenced as `sarah_groff_palermo.jpg` while on [Sarah's page](https://sfpc.io/people/sarah-groff-palermo/), it is referenced as `sarah_groff-palermo.jpg`

Notice the dash vs underscore. I have a feeling like fixing it at one place (the page or the list) breaks the other place..?

**Comment by solon** [comment]
Fixed in 271ea08

**Comment by gregsadetsky** [comment]
Small note that the photo now appears on the [/people/](https://sfpc.io/people/) page but is 404 on [Sarah's page](https://sfpc.io/people/sarah-groff-palermo/)

**Comment by solon** [comment]
@gregsadetsky thanks for the heads up. Looking into it now.
