### ISSUE TITLE
proposal: disable merge commits

### ISSUE THREAD

**Issue by solon** [SFPC/sfpc.github.io#201]
I suggest disabling this option in [settings](https://github.com/SFPC/sfpc.github.io/settings)...

<img width="648" alt="image" src="https://user-images.githubusercontent.com/48528/59645224-cde75300-913e-11e9-96b0-809a8420bf1c.png">

...so that we don't get merge commits like these:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/48528/59645262-f53e2000-913e-11e9-91b4-b2818a50a04b.png">

...which pollute the commit history, IMO. 

Thoughts?

**Comment by rileyjshaw** [comment]
Into it. Done.
