### ISSUE TITLE
people are maybe too small on full width (960pix) pages

### ISSUE THREAD

**Issue by ofZach** [SFPC/sfpc.github.io#81]
I think there used to be 4 or 5 columns before?  with people photos this small there's alot of misalignment with the icons dropping to the second line, etc. 

![screen shot 2014-12-31 at 10 08 14 am](https://cloud.githubusercontent.com/assets/142897/5588352/052aee68-90d5-11e4-8f39-a76189364f0b.png)

**Comment by caseyg** [comment]
Good to close this @ofZach?

**Comment by ofZach** [comment]
sure - I think we can revisit this.  Will be cool to do something less grid like at some point....  thanks!
